Bootstrap: docker
From: debian:trixie

%labels
    Author thomas.jacquot@ligo.org
    Description GBM Targeted Search environment

%environment
    export VIRTUAL_ENV=up2dategts
    export PATH=/opt/up2dategts/bin:$PATH
%post
    apt update -y
    apt install -y\
        git \
        build-essential \
        cmake \
        gfortran \
        libcfitsio-dev \
        pkg-config \
        ca-certificates \
        perl \
        curl \
	    python3 \
	    python3-venv

    #Instructions to install response generator
    apt install -y libastro-fits-cfitsio-perl
    curl --output gbmrsp-2.0.10.tar.bz2 https://fermi.gsfc.nasa.gov/ssc/data/analysis/gbm/gbmrsp-2.0.10.tar.bz2 
    tar xvjf gbmrsp-2.0.10.tar.bz2
    cd gbmrsp-2.0
    mkdir build
    cd build
    cmake ../src
    make
    make install
    
    cd 

    #Creation of the virtual env
    python3 -m venv /opt/up2dategts

    . /opt/up2dategts/bin/activate

    python3 -m pip install --upgrade pip setuptools wheel

    cd /opt
    git clone -b GBM-TTE-sim --filter=blob:none --depth=1 https://github.com/Thomas-JACQUOT/gamma-ray-targeted-search.git

    cd gamma-ray-targeted-search

    pip install -r requirements.txt

    pip install h5py

%test
    /opt/up2dategts/bin/python --version
    /opt/up2dategts/bin/pip list
    /opt/up2dategts/bin/python -c "
import gdt
print('gdt import successful')
"