Bootstrap: docker
From: debian:trixie

%labels
    Author thomas.jacquot@ligo.org
    Description GBM Targeted Search environment

%environment
    export VIRTUAL_ENV=up2dategts
    export PATH=/opt/up2dategts/bin:$PATH
%post
    apt update -y
    apt install -y\
        git \
        CMake \
        gcc \
        perl>5.6 \
        cfitsio \
	    python3 \
	    python3-venv

    #curl http://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio_latest.tar.gz
    python3 -m venv /opt/up2dategts

    source /opt/up2dategts/bin/activate

    python3 -m pip install --upgrade pip setuptools wheel

    cd /opt
    git clone -b GBM-TTE-sim --filter=blob:none --depth=1 https://github.com/Thomas-JACQUOT/gamma-ray-targeted-search.git

    cd gamma-ray-targeted-search

    pip install -r requirements.txt

    pip install h5py
%runscript
    source /opt/up2dategts/bin/activate

%test
    /opt/up2dategts/bin/python --version
    /opt/up2dategts/bin/pip list
    /opt/up2dategts/bin/python -c "
import gdt
print('gdt import successful')
"