#[prior-mass1]
#name = gaussian
#min = 1.0
#max = 3.0
#mean = 1.4
#var = 0.2
#
#[prior-mass2]
#name = gaussian
#min = 1.0
#max = 3.0
#mean = 1.4
#var = 0.2
#
#[constraint-mass_order]
#name = custom
#constraint_arg = mass2 <= mass1
#
#[prior-distance]
#name = uniform
#max = 5
#min = 500
